export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Navbar from "@/components/navbar/Navbar"
import Footer from "@/components/footer/Footer"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
