export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen transition-colors duration-300 flex flex-col justify-between">
        <ThemeProvider>
          <div className="max-w-screen-lg mx-auto px-4 sm:px-8 lg:px-16 flex-grow">
            <Navbar />
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
